### ISSUE TITLE
server.plugins.bookshelf.model is not a function

### ISSUE THREAD

**Issue by rzig** [lob/hapi-bookshelf-models#32]
Hi. I just set up `hapi-bookshelf-models` and ran into an issue. I set up `hapi-bookshelf-models` in my server like this:

    server.register([
      {
        register: require("hapi-bookshelf-models"),
        options: {
          knex: {
            client: "pg",
            connection: {
              host: "localhost",
              user: "postgres",
              password: "postgres",
              database: "postgres",
              port: 5432
            }
          }
        },
        plugins: ["registry"],
        models: "./models",
        collections: "./collections"
      }
    ]);

The `./models` folder contains a single file, `device.js`, which looks like this:

    module.exports = function(baseModel, bookshelf) {
      return baseModel.extend({
        tableName: "devices"
      })
    }

The `./collections` folder contains one file, `devices.js`, which looks like this:

    module.exports = function (baseCollection, bookshelf) {
      return baseCollection.extend({
        model: bookshelf.model('device')
      });
    };

I added a simple route to my server, which looks like this:

    server.route({
      method: "GET",
      path: "/hi",
      handler: (req, rep) => {
        rep(server.plugins.bookshelf.model("Device").fetchAll());
      }
    });

This should return an empty array, but instead it causes an error, saying that `server.plugins.bookshelf.model is not a function`. Here's the full stack trace:

       TypeError: Uncaught error: server.plugins.bookshelf.model is not a function
         at handler (C:\Users\Owner\Documents\code\hapi\myproject\index.js:112:34)
         at Object.internals.handler (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\handler.js:99:36)
         at request._protect.run (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\handler.js:30:23)
         at module.exports.internals.Protect.internals.Protect.run (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\protect.js:62:12)
         at exports.execute (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\handler.js:24:22)
         at each (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\request.js:380:16)
         at iterate (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\node_modules\items\lib\index.js:36:13)
         at done (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\node_modules\items\lib\index.js:28:25)
         at module.exports.internals.Auth.internals.Auth._authenticate (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\auth.js:222:16)
         at internals.Auth.authenticate (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\auth.js:197:17)
         at each (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\request.js:380:16)
         at iterate (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\node_modules\items\lib\index.js:36:13)
         at done (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\node_modules\items\lib\index.js:28:25)
         at internals.state (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\route.js:362:16)
         at each (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\lib\request.js:380:16)
         at iterate (C:\Users\Owner\Documents\code\hapi\myproject\node_modules\hapi\node_modules\items\lib\index.js:36:13)

I'm not quite sure what's going on here - am I somehow configuring it incorrectly, or is there a bug?

**Comment by robinjoseph08** [comment]
Hey @rzig,

Looks like in your config object when registering the plugin, the nesting is a bit off. The `plugins`, `models`, and `collections` properties need to be within the `options` object, not alongside it:

```js
server.register([
  {
    register: require("hapi-bookshelf-models"),
    options: {
      knex: {
        client: "pg",
        connection: {
          host: "localhost",
          user: "postgres",
          password: "postgres",
          database: "postgres",
          port: 5432
        }
      },
      plugins: ["registry"],
      models: "./models",
      collections: "./collections"
    }
  }
]);
```

That should get it working for you.

On a side note though, it might actually be a tad easier for you to use Bookshelf without this module, especially since it looks like you're just starting to create your API.

- While it makes it easier by loading in all of the models in a directory, it adds a bit of magic to the loading process that should be left explicit.
- It makes it harder to reference these models once you start fleshing out your codebase i.e. pulling your code into separate files. For you to be able to access any of your models in another file, you'll need to have access to the `server` object so you'll have to pass that around, even though you don't need the entire object.
- We don't actively maintain this repo since we don't really use it ourselves anymore.
- The [Bookshelf registry plugin](https://github.com/tgriesser/bookshelf/wiki/Plugin:-Model-Registry) is required when using this modules, but if you don't actually need it (i.e. you don't have circular dependencies with your models), then it just adds unnecessary complexity to your project.
- The creator of Hapi [frowns upon](https://gist.github.com/hueniverse/f01faf422eb038d87d57#when-should-i-not-use-multiple-plugins) using plugins in this manner.

Instead, I would recommend just `require`ing the models as you need them. That way, you can easily refer to the models and only include the ones that make sense to have in the current context:

### Without `hapi-bookshelf-models`

```js
// index.js
const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({ port: 8080 });

server.register([
  require('./routes');
], () => {});

server.start(() => console.log('Server started'));
```

```js
// routes.js
const Controller = require('./controllers/user');

exports.register = function (server, options, next) {
  server.route({
    method: 'GET',
    path: '/users',
    handler: (request, reply) => {
      reply(Controller.listUsers());
    }
  });
};
```

```js
// controllers/user.js
const User = require('../models/user');

exports.listUsers = function () {
  return User.fetchAll();
};
```

```js
// models/user.js
const Bookshelf = require('../bookshelf');

return Bookshelf.Model.extend({ tableName: 'users' });
```

### With `hapi-bookshelf-models`

```js
// index.js
const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({ port: 8080 });

server.register([
  {
    register: require("hapi-bookshelf-models"),
    options: {
      knex: {
        client: "pg",
        connection: {
          host: "localhost",
          user: "postgres",
          password: "postgres",
          database: "postgres",
          port: 5432
        }
      },
      plugins: ["registry"],
      models: "./models",
      collections: "./collections"
    }
  },
  require('./routes');
], () => {});

server.start(() => console.log('Server started'));
```

```js
// routes.js
const Controller = require('./controllers/user');

exports.register = function (server, options, next) {
  server.route({
    method: 'GET',
    path: '/users',
    handler: (request, reply) => {
      reply(Controller.listUsers(server));
    }
  });
};
```

```js
// controllers/user.js
exports.listUsers = function (server) {
  return server.plugins.bookshelf.model('User').fetchAll();
};
```

```js
// models/user.js
return function (base) {
  return base.extend({ tableName: 'users' });
}
```

However if you still want to continue using this plugin, feel free to do so, though we can't make any guarantees about active support. Hope this helped! 😄
